name: shade
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  file_picker:
  flutter_boxicons:
  flutter_launcher_icons:
  flutter_native_splash:
  flutter_screenutil:
  flutter_spinkit:
  flutter_gl:
  flutter_prism:
  flutter_riverpod:
  flutter_svg:
  flex_color_picker:
  introduction_screen:
  equatable:
  is_first_run:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter_launcher_icons:
  image_path_android: "assets/icon.png"
  android: true
  adaptive_icon_background: "#313131"
  adaptive_icon_foreground: "assets/icon.png"
  min_sdk_android: 29

flutter_native_splash:
  color: "#1E1E1E"
  android: true
  ios: true



flutter:


  uses-material-design: true

  assets:
    - assets/

  fonts:
    - family: Nunito
      fonts:
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-Black.ttf
        - asset: fonts/Nunito-ExtraBold.ttf
        - asset: fonts/Nunito-ExtraLight.ttf
        - asset: fonts/Nunito-Italic.ttf
        - asset: fonts/Nunito-Light.ttf
        - asset: fonts/Nunito-Medium.ttf
        - asset: fonts/Nunito-Regular.ttf
        - asset: fonts/Nunito-SemiBold.ttf
